version: "3.9"

services:
  api:
    build: .
    container_name: cedipay-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: cedipay-db
    environment:
      POSTGRES_USER: cedipay
      POSTGRES_PASSWORD: cedipay
      POSTGRES_DB: cedipay
    ports:
      - "5432:5432"
    volumes:
      - cedipay_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cedipay-redis
    ports:
      - "6379:6379"

volumes:
  cedipay_data:
